package leetcode.solved;
import java.util.Hashtable;
//You are given two strings s and t. 
//
// String t is generated by random shuffling string s and then add one more lett
//er at a random position. 
//
// Return the letter that was added to t. 
//
// 
// Example 1: 
//
// 
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
// 
//
// Example 2: 
//
// 
//Input: s = "", t = "y"
//Output: "y"
// 
//
// Example 3: 
//
// 
//Input: s = "a", t = "aa"
//Output: "a"
// 
//
// Example 4: 
//
// 
//Input: s = "ae", t = "aea"
//Output: "a"
// 
//
// 
// Constraints: 
//
// 
// 0 <= s.length <= 1000 
// t.length == s.length + 1 
// s and t consist of lower-case English letters. 
// 
// Related Topics 位运算 哈希表 
// 👍 220 👎 0

public class Leetcode389{
	public static void main(String[] args) {
		Solution solution = new Leetcode389().new Solution();
		
	}

//leetcode submit region begin(Prohibit modification and deletion)
class Solution {
    public char findTheDifference(String s, String t) {
		char diffChar = '0';
		Hashtable<Character, Integer> map = new Hashtable<>();
		for (int i = 0; i < s.length(); i++) {
			char tmp = s.charAt(i);
			if (map.containsKey(tmp))
				map.put(tmp, map.get(tmp) + 1);
			else
				map.put(tmp, 1);
		}
		for (int i = 0; i < t.length(); i++) {
			if (!map.containsKey(t.charAt(i))) {
				diffChar = t.charAt(i);
				break;
			}
			int count = map.get(t.charAt(i));
			if (count > 0)
				map.put(t.charAt(i), count - 1);
			else {
				diffChar = t.charAt(i);
				break;
			}
		}
		return diffChar;
    }
}
//leetcode submit region end(Prohibit modification and deletion)

}